from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome(executable_path="/Users/Jaishree.Bawaskar/Desktop/chromedriver_win32/chromedriver.exe")
driver.get('https://www.facebook.com')
assert "Facebook" in driver.title
fn = driver.find_element_by_name("firstname")
fn.send_keys("jayu")
sn = driver.find_element_by_name("lastname")
sn.send_keys("bawaskar")
user = driver.find_element_by_name("reg_email__")
user.send_keys("demoassignment7@gmail.com")
user1 = driver.find_element_by_name("reg_email_confirmation__")
user1.send_keys("demoassignment7@gmail.com")
pwd = driver.find_element_by_id("u_0_x")
pwd.send_keys("jaishree123")
day = driver.find_element_by_id("day")
day.send_keys("29")
month = driver.find_element_by_id("month")
month.send_keys("jan")
year = driver.find_element_by_id("year")
year.send_keys("1998")
female = driver.find_element_by_id("u_0_5")
#male = driver.find_element_by_id("u_0_6")
female.click()
signup = driver.find_element_by_id("u_0_15")
signup.click()

#elem.send_keys(Keys.RETURN)
# driver.close()